name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libusb-1.0-0-dev

      - name: Install system deps (macOS)
        if: runner.os == 'macOS'
        run: brew install libusb

      - name: Install package
        run: pip install -e ".[dev]"

      - name: Lint
        run: ruff check sm2can/

      - name: Test
        run: pytest --tb=short -q

  publish-pypi:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
